server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lazyTaken?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: maxing19971211
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.lazytaken.lazybackend.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  #configLocation: classpath:/mybatis-config.xml

